import { useEffect, useState } from "react";
import type { ManagementApi, Project, TaskStatus, TaskSummary } from "../../api/management-api";
import { formatTime, statusLabel } from "../dashboard/DashboardPage";

export function TaskListPage({ api, onOpenTask }: { api: ManagementApi; onOpenTask: (taskId: string) => void }) {
  const [tasks, setTasks] = useState<TaskSummary[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [status, setStatus] = useState<TaskStatus | "">(""); const [projectId, setProjectId] = useState(""); const [error, setError] = useState("");
  useEffect(() => { let alive = true; Promise.all([api.getProjects(), api.getTasks({ status: status || undefined, projectId: projectId || undefined })]).then(([nextProjects, result]) => { if (alive) { setProjects(nextProjects); setTasks(result.items); } }).catch((cause: unknown) => alive && setError(cause instanceof Error ? cause.message : "无法读取任务")); return () => { alive = false; }; }, [api, status, projectId]);
  return <section className="page-stack"><div className="filter-row"><label>任务状态<select value={status} onChange={(event) => setStatus(event.target.value as TaskStatus | "")}><option value="">全部状态</option><option value="active">进行中</option><option value="completed">已完成</option><option value="closed">已关闭</option></select></label><label>所属项目<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">全部项目</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.title}</option>)}</select></label></div>{error ? <section className="notice error">{error}</section> : <section className="surface"><div className="table">{tasks.length ? tasks.map((task) => <button className="row-button task-row" key={task.id} onClick={() => onOpenTask(task.id)}><span><strong>{task.title || "未命名任务"}</strong><small>{task.current_step || "等待现场输入"}</small></span><span className={`status ${task.status}`}>{statusLabel(task.status)}</span><time>{formatTime(task.updated_at)}</time></button>) : <div className="empty">当前筛选条件下暂无任务。</div>}</div></section>}</section>;
}
